development:
  adapter: mysql2
  database: profile_development
  pool: 5
  username: postgres
  password:
  host: localhost

test:
  adapter: mysql2
  database: profile_test
  pool: 5
  username: default
  password: defaultpassword
  host: localhost

staging:
  adapter: postgresql
  database: profile_empty
  pool: 5
  username: postgres
  password:
  host: localhost

production:
  adapter: postgresql
  database: profile_production
  pool: 5
  username: postgres
  password: JnmRy2gBw2GZsgn
  host: localhost
